### ISSUE TITLE
Observer features 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/yr-patches#9]
**Feature request**

As an observer, I want the ability to see:

- Underwater units of all players
- What other players are building when clicking on production buildings. (MO has this with Ares)

**Comment by Belonit** [comment]
`Underwater units of all players` - @Starkku [Implemented ](https://github.com/Phobos-developers/Phobos/blob/525d8bba72b66fc43e2509b3fa3fa9064731409d/src/Ext/Techno/Hooks.cpp#L617)this in Phobos, it can be easily ported to the current one
yr-patches
